object Versions {
    const val jaxrsVersion = "2.0"
    const val jasyptVersion = "2.1.0"
    const val bouncyCastleVersion = "1.70"
    const val swaggerVersion = "1.6.2"
    const val guavaVersion = "29.0-jre"
    const val ciVersion = "2.1.0"
    const val commonIo = "2.7"
    const val jjwtVersion = "0.9.0"
    const val micrometerVersion = "1.6.6"
    const val okHttpVersion = "4.9.0"
    const val Kotlin = "1.6.0"
    const val coroutinesCore = "1.3.1"
    const val iamSdkVersion = "1.0.21-SNAPSHOT"
}
